services:
  dockerproxy:
    container_name: docker_socket_proxy
    image: tecnativa/docker-socket-proxy:0.1
    restart: unless-stopped
    networks:
      - docker_sock
    ports:
      - 2375
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - LOG_LEVEL=warning
      - CONTAINERS=1

  traefik:
    hostname: traefik
    image: traefik:2.11
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - "TZ"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
      - docker_sock

networks:
  traefik:
    name: traefik
    ipam:
      config:
        - subnet: ${TRAEFIK_SUBNET}
  docker_sock:
    name: docker_sock
