services:
  dockerproxy:
    container_name: docker_socket_proxy
    image: tecnativa/docker-socket-proxy:0.1
    restart: unless-stopped
    networks:
      - docker_sock
    ports:
      - 2375
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - LOG_LEVEL=warning
      - CONTAINERS=1

  traefik:
    hostname: traefik
    image: traefik:2.11
    container_name: traefik
    restart: unless-stopped
    depends_on:
      - dockerproxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ
      - CF_API_EMAIL
      - CF_API_KEY
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUMES_DIR}/acme:/etc/traefik/acme
      - ${VOLUMES_DIR}/log:/var/log
      - ./conf/traefik-dynamic.yml:/etc/traefik/config/dynamic.yml
      - ./conf/traefik-static.${TARGET}.yml:/etc/traefik/traefik.yml
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard.service=api@internal
      - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAINNAME}`)
    networks:
      - traefik
      - docker_sock

  whoami:
    image: containous/whoami
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)

networks:
  traefik:
    name: traefik
    ipam:
      config:
        - subnet: ${TRAEFIK_SUBNET}
  docker_sock:
    name: docker_sock
