services:
  traefik:
    env_file:
      - dnschallenge.env
    environment:
      - "TZ"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUMES_DIR}/acme:/etc/traefik/acme
      - ${VOLUMES_DIR}/log:/var/log
      - ./conf/traefik-dynamic.yml:/etc/traefik/config/dynamic.yml
      - ./conf/traefik-static.prod.yml:/etc/traefik/traefik.yml
