version: "3.5"
services:
  traefik:
    env_file:
      - dnschallenge.env
    environment:
      - "TZ"
    security_opt:
      - no-new-privileges:true
    command:
      - --api.dashboard=false
      - --providers.file.watch=true
      - --providers.file.directory=/etc/traefik/config/
      # Get Docker as the provider
      - --providers.docker=true
      - --providers.docker.endpoint=tcp://dockerproxy:2375
      - --providers.docker.network=traefik
      - --providers.docker.exposedbydefault=false
      # Settle the ports for the entry points
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=myresolver
      - --entrypoints.websecure.http.tls.domains[0].main=*.${DOMAINNAME}
      - --entrypoints.websecure.http.tls.domains[0].sans=${DOMAINNAME}
      # Logging
      - --log.level=${LOG_LEVEL}
      - --log.filePath=/var/log/traefik.log
      - --accesslog=true
      - --accesslog.filepath=/var/log/accesslog.log
      - --accesslog.filters.statuscodes=401,400-499,502
      - --accesslog.filters.retryattempts
      - --accesslog.filters.minduration=10ms
      # Letsencrypt
      - --certificatesresolvers.myresolver.acme.dnschallenge.provider=${DNS_CHALLENGE_PROVIDER}
      - --certificatesresolvers.myresolver.acme.email=${CERT_EMAIL}
      - --certificatesresolvers.myresolver.acme.caserver=${CA_SERVER}
      - --certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme/acme.json
