version: '2.1'
services:
  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # TODO: nicht das Unix-Socket verwenden, siehe https://docs.traefik.io/providers/docker/#docker-api-access  https://medium.com/@containeroo/t-22da9cb3e78c
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - traefik
  whoami:
    image: containous/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)
    networks:
      - traefik
networks:
  traefik:
    name: traefik
