version: "3.5"
services:
  dockerproxy:
    container_name: docker_socket_proxy
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    networks:
      - docker_sock
    ports:
      - 2375
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - LOG_LEVEL=info
      - CONTAINERS=1

  traefik:
    hostname: traefik
    image: traefik:2.4
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - "TZ={{ TIME_ZONE }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUMES_DIR}/acme:/etc/traefik/acme
      - ${VOLUMES_DIR}/log:/var/log
      - ${VOLUMES_DIR}/config:/etc/traefik/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
      - docker_sock

networks:
  traefik:
    name: traefik
  docker_sock:
    name: docker_sock
