version: "3.5"
services:
  traefik:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUMES_DIR}/acme:/etc/traefik/acme
      - ${VOLUMES_DIR}/log:/var/log
      - ./conf/traefik-dynamic.yml:/etc/traefik/config/dnamic.yml
      - ./conf/traefik-static.dev.yml:/etc/traefik/traefik.yml
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard.service=api@internal
      - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.docker.localhost`)

  whoami:
    image: containous/whoami
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)
