services:
  dockerproxy:
    container_name: docker_socket_proxy
    image: tecnativa/docker-socket-proxy:latest
    restart: unless-stopped
    networks:
      - docker_sock
    ports:
      - 2375
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - haproxy_state:/var/lib/haproxy
    environment:
      - LOG_LEVEL=warning
      - CONTAINERS=1
      - TIMEOUT_CONNECT=5000
      - TIMEOUT_CLIENT=50000
      - TIMEOUT_SERVER=50000

  traefik:
    hostname: traefik
    image: traefik:3.6
    container_name: traefik
    restart: unless-stopped
    depends_on:
      - dockerproxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUMES_DIR}/acme:/etc/traefik/acme
      - ${VOLUMES_DIR}/log:/var/log
      - ${VOLUMES_DIR}/certs:/certs:ro
      - ./conf/traefik-dynamic.yml:/etc/traefik/config/dynamic.yml
      - ./conf/traefik-static.${TARGET}.yml:/etc/traefik/traefik.yml
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard.service=api@internal
    networks:
      - traefik
      - docker_sock

  whoami:
    image: containous/whoami
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true

volumes:
  haproxy_state:

networks:
  traefik:
    name: traefik
    ipam:
      config:
        - subnet: ${TRAEFIK_SUBNET}
  docker_sock:
    name: docker_sock
