# Docker configuration backend
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: traefik
defaultEntryPoints:
  - websecure
  - web
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
certificatesResolvers:
  myresolver:
    acme:
      email: kontakt@e-nigma.xyz
      storage: acme.json
     # use staging server for testing:
     # caServer: https://acme-staging-v02.api.letsencrypt.org/directory 
      httpChallenge:
        entryPoint: web
api:
  insecure: true        # Dashboard
